name: Async-gpt-frontend
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - main
  #   paths:
  #     - '.github/workflows/*'
permissions:
  id-token: write
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-dependencies
        uses: ./.github/actions/cached-dependencies
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-dependencies
        uses: ./.github/actions/cached-dependencies
      - name: Build website
        run: npm run build
      - name: Build export
        run: npm run export
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out-files
          path: out

  deploy-uat:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: out-files
          path: out
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::255697205252:role/gh-action-role
          role-session-name: S3Deployment
          aws-region: ap-southeast-2
      - name: Deploy to PROD S3
        run: |
          aws s3 sync out ${{ secrets.S3_UAT_BUCKET }}

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: out-files
          path: out
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::255697205252:role/gh-action-role
          aws-region: ap-southeast-2
      - name: Deploy to PROD S3
        run: |
          aws s3 sync out ${{ secrets.S3_PROD_BUCKET }}
      

